[project]
name = "ith-python"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14.2"
dependencies = [
    "loguru>=0.7.3",
    "numba>=0.63.1",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "rich>=14.2.0",
    "scipy>=1.17.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.14.12",
]
